<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Arman" failures="1" tests="7" name="testcases.LoginTest" time="39.318" errors="0" timestamp="2023-04-28T17:07:12 EDT" skipped="0">
  <testcase classname="testcases.LoginTest" name="verifyLoginWithValidCredentials" time="5.804"/>
  <system-out/>
  <testcase classname="testcases.LoginTest" name="verifyLoginWithInvalidCredentials" time="5.613">
    <failure message="Expected Warning Message is not displayed expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected Warning Message is not displayed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at testcases.LoginTest.verifyLoginWithInvalidCredentials(LoginTest.java:37)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <system-out/>
  <testcase classname="testcases.LoginTest" name="verifyLoginWithInvalidEmailAndValidPassword" time="5.694"/>
  <system-out/>
  <testcase classname="testcases.LoginTest" name="verifyLoginWithValidEmailAndInvalidPassword" time="5.556"/>
  <system-out/>
  <testcase classname="testcases.LoginTest" name="verifyLoginWithEmptyBoxes" time="5.464"/>
  <system-out/>
  <testcase classname="testcases.LoginTest" name="verifyLoginWithEmptyEmailBoxAndValidPasswod" time="5.584"/>
  <system-out/>
  <testcase classname="testcases.LoginTest" name="verifyLoginWithEmptyPasswordBoxAndValidEmail" time="5.603"/>
  <system-out/>
</testsuite> <!-- testcases.LoginTest -->
